### ISSUE TITLE
安装时，提示依赖关系：shadowsocks-libqtshadowsocks 依赖于 libqtshadowsocks

### ISSUE THREAD

**Issue by Tanlet** [librehat/libQtShadowsocks#15]
环境：Debian7.8,Gnome3.14.1
我已经安装好所需要的依赖并打包deb成功。但是，安装时出错：
命令：sudo dpkg -i shadowsocks-libqtshadowsocks_1.4.1-1_amd64.deb 
结果：
正准备解包 shadowsocks-libqtshadowsocks_1.4.1-1_amd64.deb  ...
正在将 shadowsocks-libqtshadowsocks (1.4.1-1) 解包到 (1.4.1-1) 上 ...
dpkg: 依赖关系问题使得 shadowsocks-libqtshadowsocks 的配置工作不能继续：
 shadowsocks-libqtshadowsocks 依赖于 libqtshadowsocks；然而：
  未安装软件包 libqtshadowsocks。

dpkg: 处理软件包 shadowsocks-libqtshadowsocks (--install)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 shadowsocks-libqtshadowsocks
这的确有点搞笑！请问是我的操作失误吗？

**Comment by Tanlet** [comment]
呃！原来打包出两个deb包。Sorry

**Comment by Tanlet** [comment]
我已安装两个deb包：libqtshadowsocks_1.4.1-1_amd64.deb和shadowsocks-libqtshadowsocks_1.4.1-1_amd64.deb
还是没法打包shadowsocks-qt5，仍然提示：
Unmet build dependencies: libqtshadowsocks-dev (>= 1.4.0)
我猜原因是：libqtshadowsocks_1.4.1-1_amd64.deb安装包名是libqtshadowsocks，并不是libqtshadowsocks-dev。

**Comment by Tanlet** [comment]
我去！竟然是三个deb包。好吧！我又错了

**Comment by librehat** [comment]
自问自答了吧…
