### ISSUE TITLE
求救:shadowsocks-libqss.exe - 無法找到輸入點

### ISSUE THREAD

**Issue by huangdog** [librehat/libQtShadowsocks#16]
http://www.librehat.com/three-minutes-to-set-up-shadowsocks-server-on-windows/
你好，我已經按照以上的教程將步驟做足了，為什麼會出現以下錯誤？

無法找到程序輸入點 inet_ntop (在動態連結程式庫 WS2_32.dll)。 
http://i.imgbox.com/m9cvQaQe.png

**Comment by librehat** [comment]
Windows XP will never get supported
