### ISSUE TITLE
Buggy Table

### ISSUE THREAD

**Issue by XhstormR** [librehat/libQtShadowsocks#19]
使用table加密直接闪退,而改成rc4-md5就能正常使用.

**Comment by librehat** [comment]
是用的shadosocks-libqss这个client吗？什么平台？

**Comment by XhstormR** [comment]
完全参照你BLOG中的'Windows下三分钟搭建Shadowoscks服务器端'文章做的,是在windows平台.

**Comment by librehat** [comment]
Table is buggy and won't be able to pass `selfTest()`.

**Comment by librehat** [comment]
I can also confirm that my ARMv7 board doesn't have this issue. So it may be an issue of signed and unsigned characters.
