### ISSUE TITLE
Cipher test failed？

### ISSUE THREAD

**Issue by MidoriYakumo** [librehat/libQtShadowsocks#26]
~ » shadowsocks-libqss -c /etc/shadowsocks/config.json
"Initialising ciphers..."
"TABLE (table) initialised."
"Listen UDP socket state changed to QAbstractSocket::BoundState "
"Running in local mode."
"TCP server listen at port 8883"
Cipher test failed.

然而用golang版的ss就没有问题

**Comment by librehat** [comment]
用的什么版本？shadowsocks-libqss -v看一下？

**Comment by MidoriYakumo** [comment]
Shadowsocks-libQtShadowsocks 1.4.1

**Comment by librehat** [comment]
最新的是1.6.1了，都差了好几个版本。前面某个版本的TABLE加密有问题，已经修复了的。
