### ISSUE TITLE
Can't be compiled with Bortan-1.11

### ISSUE THREAD

**Issue by eitanlevy97** [librehat/libQtShadowsocks#27]
I directly changed BOTAN_VERSION in project file itself, (1.10 -> 1.11), but when I trying to compile the library got the following errors:

cipher.cpp: In static member function ‘static bool QSS::Cipher::isSupported(const QByteArray&)’:
cipher.cpp:128:16: error: ‘have_algorithm’ is not a member of ‘Botan’
         return Botan::have_algorithm(algorithm);
                ^
Makefile.libQtShadowsocks:646: recipe for target 'cipher.o' failed
make[1]: *** [cipher.o] Error 1
make[1]: Leaving directory '/home/XXX/Source/libQtShadowsocks/lib'
Makefile:43: recipe for target 'sub-lib-libQtShadowsocks-pro-make_first-ordered' failed
make: *** [sub-lib-libQtShadowsocks-pro-make_first-ordered] Error 2

**Comment by librehat** [comment]
Looks like this function is removed from 1.11. I'll go to use [`get_cihper_mode`](http://botan.randombit.net/doxygen/namespaceBotan.html#a16a061a690987a3a3c29d38641e209e4) to test if the algorithm is supported or no.
