### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by zhuyijun1573** [librehat/libQtShadowsocks#28]
dpkg-buildpackage -uc -us -b 报错 tail: 无法打开"debian/changelog" 读取数据: 没有那个文件或目录
dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1
 怎么回事啊？？？

**Comment by librehat** [comment]
不可能没有这个文件的。自己复查一下自己的操作。

**Comment by ysh329** [comment]
same problem……

**Comment by addsun** [comment]
同样问题，，你是如何解决的？

**Comment by SummerSun** [comment]
same problems here. just clone the repo, surely there is no debian kind of directory here.

**Comment by SummerSun** [comment]
Checked the branches, use **stable** , instead of **master**

**Comment by bugxch** [comment]
same problem， how to fix it?

**Comment by dd404x** [comment]
+1
