### ISSUE TITLE
您好，你博客config.json文件 范例文件连接失效了，另外咨询启用多用户问题

### ISSUE THREAD

**Issue by ntgeralt** [librehat/libQtShadowsocks#30]
你好，我刚接触你的方式，想尝试在win下建立ss服务端。请教一下能否添加多用户及方式，Thanks

**Comment by librehat** [comment]
链接更新了：https://github.com/librehat/libQtShadowsocks/blob/master/shadowsocks-libqss/config.json

不支持多用户的配置
