### ISSUE TITLE
Windows10运行报错

### ISSUE THREAD

**Issue by Archieeeeee** [librehat/libQtShadowsocks#34]
64位libqss以客户端命令运行，提示：
Qt: Untested Windows version 10.0 detected!
Unknown options: p, k, m, b, l.

**Comment by librehat** [comment]
你的运行命令是什么？

**Comment by librehat** [comment]
我在Windows 10反复运行测试了，没有问题。你说的情况更像是你在1.6版上用了1.7版的命令。请等待本月1.7版正式发布
