### ISSUE TITLE
windows下构建时找不到botan头文件

### ISSUE THREAD

**Issue by LooJee** [librehat/libQtShadowsocks#37]
你好，我下了libQtShadowsocks的release1.6.1版本，到windows上编译，使用的编译器是vs2013的，qt版本是msvc2013-5.5.0，botan是1.11.19。
我在libQtShadowsocks.pro中添加了一句INCLUDEPATH += C:\Botan\include\botan-1.11用来指定botan头文件的路径，但是构建项目的时候却报找不到头文件的错误，具体错误如下：D:\libQtShadowsocks\libQtShadowsocks-1.6.1\lib\cipher.cpp:23: error: C1083: 无法打开包括文件: “botan/auto_rng.h”: No such file or directory
D:\libQtShadowsocks\libQtShadowsocks-1.6.1\lib\cipher.h:36: error: C1083: 无法打开包括文件: “botan/pipe.h”: No such file or directory
D:\libQtShadowsocks\libQtShadowsocks-1.6.1\lib\controller.cpp:25: error: C1083: 无法打开包括文件: “botan/init.h”: No such file or directory
D:\libQtShadowsocks\libQtShadowsocks-1.6.1\lib\chacha.cpp:25: error: C1083: 无法打开包括文件: “botan/loadstor.h”: No such file or directory
本人菜鸟，还请大神不吝赐教。。。

**Comment by librehat** [comment]
botan要自己编译安装好。
