### ISSUE TITLE
运行后通过外网IP无法访问

### ISSUE THREAD

**Issue by sharpdeep** [librehat/libQtShadowsocks#38]
运行后本地可以通过127.0.0.1连接成功，通过外网IP连接失败

**Comment by librehat** [comment]
你本地监听地址要设置为0.0.0.0

**Comment by sharpdeep** [comment]
Server本来就已经设置0.0.0.0，配置如下：
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"123456",
    "timeout":600,
    "method":"aes-256-cfb",
    "http_proxy": false
}
还是不能外网IP连接

**Comment by librehat** [comment]
你本机防火墙打开了吗？还有，路由器要设置好端口转发或者开启DMZ，不然公网IP是不能直接访问你的电脑的
